# Generated by Django 3.1.4 on 2020-12-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_spotlight_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='favourite_tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
