# Generated by Django 3.1.4 on 2020-12-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_favourite_tea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite_tea',
            name='price',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spotlight_body',
            name='price',
            field=models.IntegerField(max_length=100),
        ),
    ]
