# Generated by Django 3.1.4 on 2020-12-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20201224_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite_tea',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spotlight_body',
            name='price',
            field=models.IntegerField(),
        ),
    ]
